### ISSUE TITLE
Very hard to add device to proxyrack

### ISSUE THREAD

**Issue by tqdungctuct** [spiritLHLS/proxyrack-one-click-command-installation#5]
I used this script to install proxyrack. It install successfully but i can't add device to proxyrack. Is it a bug of proxyrack? Log of docker is 
```
Please check your internet connection and try again.
Using provided UUID: B9F105A57917E043C00EED3094EAF92A349C80635321xxxxxxxxxxxxxxxxxxxx
Updating Proxyrack...
--2024-01-23 10:14:03--  https://app-updates.sock.sh/peerclient/script/script.js
Resolving app-updates.sock.sh (app-updates.sock.sh)... 147.182.212.102
Connecting to app-updates.sock.sh (app-updates.sock.sh)|147.182.212.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1682231 (1.6M) [application/javascript]
Saving to: 'script.js'

     0K .......... .......... .......... .......... ..........  3%  143K 11s
    50K .......... .......... .......... .......... ..........  6%  286K 8s
   100K .......... .......... .......... .......... ..........  9% 30.4M 5s
   150K .......... .......... .......... .......... .......... 12%  219M 4s
   200K .......... .......... .......... .......... .......... 15%  288K 4s
   250K .......... .......... .......... .......... .......... 18%  101M 3s
   300K .......... .......... .......... .......... .......... 21%  291M 3s
   350K .......... .......... .......... .......... .......... 24%  361M 2s
   400K .......... .......... .......... .......... .......... 27%  281K 2s
   450K .......... .......... .......... .......... .......... 30%  290M 2s
   500K .......... .......... .......... .......... .......... 33%  328M 2s
   550K .......... .......... .......... .......... .......... 36%  278M 2s
   600K .......... .......... .......... .......... .......... 39%  157M 1s
   650K .......... .......... .......... .......... .......... 42%  287M 1s
   700K .......... .......... .......... .......... .......... 45%  334M 1s
   750K .......... .......... .......... .......... .......... 48%  242M 1s
   800K .......... .......... .......... .......... .......... 51%  237M 1s
   850K .......... .......... .......... .......... .......... 54%  295K 1s
   900K .......... .......... .......... .......... .......... 57% 85.0M 1s
   950K .......... .......... .......... .......... .......... 60% 98.9M 1s
  1000K .......... .......... .......... .......... .......... 63%  195M 1s
  1050K .......... .......... .......... .......... .......... 66% 77.0M 1s
  1100K .......... .......... .......... .......... .......... 70%  345M 0s
  1150K .......... .......... .......... .......... .......... 73% 80.5M 0s
  1200K .......... .......... .......... .......... .......... 76%  129M 0s
  1250K .......... .......... .......... .......... .......... 79%  239M 0s
  1300K .......... .......... .......... .......... .......... 82%  220M 0s
  1350K .......... .......... .......... .......... .......... 85%  152M 0s
  1400K .......... .......... .......... .......... .......... 88%  218M 0s
  1450K .......... .......... .......... .......... .......... 91%  243M 0s
  1500K .......... .......... .......... .......... .......... 94%  258M 0s
  1550K .......... .......... .......... .......... .......... 97%  196M 0s
  1600K .......... .......... .......... .......... ..        100%  211M=1.1s

2024-01-23 10:14:04 (1.52 MB/s) - 'script.js' saved [1682231/1682231]

Update done!
Error: ENOENT: no such file or directory, unlink '/Roaming/PoP/log.log'
    at Object.unlinkSync (fs.js:1136:3)
    at _0x2c25ab (/app/script.js:1:1676538)
    at _0x384958 (/app/script.js:1:1676778)
    at Object.<anonymous> (/app/script.js:1:1680542)
    at Object.<anonymous> (/app/script.js:1:1680605)
    at _0x34ba2d (/app/script.js:1:181281)
    at /app/script.js:1:182218
    at Object.<anonymous> (/app/script.js:1:182251)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '/Roaming/PoP/log.log'
}
sending
[Error: ENOENT: no such file or directory, open './go_version.txt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './go_version.txt'
}
Error:  connect ECONNREFUSED 154.49.96.42:80
{ localVersion: '', remoteVersion: '56' }
downloading app
sending
Error:  connect ECONNREFUSED 23.227.143.219:80
{ success: true }
sending
writing 56 -> ./go_version.txt
written
go app started at: 1706004849

connecting to home: 1706004849

Error:  connect ECONNREFUSED 23.227.142.26:80
connected to home: 1706004849

sending
Error:  connect ECONNREFUSED 154.49.96.82:80
sending
Error:  connect ECONNREFUSED 38.84.70.83:80
sending
Error:  connect ECONNREFUSED 209.205.197.226:80
sending
Error:  connect ECONNREFUSED 154.49.96.42:80
sending
Error:  connect ECONNREFUSED 23.227.143.219:80
sending
Error:  connect ECONNREFUSED 38.84.70.83:80
sending
Error:  connect ECONNREFUSED 23.227.143.219:80
sending
Error:  connect ECONNREFUSED 23.227.142.26:80
sending
Error:  connect ECONNREFUSED 154.49.96.42:80
sending
Error:  connect ECONNREFUSED 209.205.197.226:80

```

**Comment by spiritLHLS** [comment]
The corresponding official container image hasn't been maintained by an administrator for almost half a year now, and I've tried fixes to no avail.
